=begin
#securityapi

#The security APIs help you detect and block security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveSecurityApiClient::StringInsecureDeserializationJsonDetection
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StringInsecureDeserializationJsonDetection' do
  before do
    # run before each test
    @instance = CloudmersiveSecurityApiClient::StringInsecureDeserializationJsonDetection.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StringInsecureDeserializationJsonDetection' do
    it 'should create an instance of StringInsecureDeserializationJsonDetection' do
      expect(@instance).to be_instance_of(CloudmersiveSecurityApiClient::StringInsecureDeserializationJsonDetection)
    end
  end
  describe 'test attribute "successful"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "contained_json_insecure_deserialization_attack"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "original_input"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
