=begin
#securityapi

#The security APIs help you detect and block security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveSecurityApiClient::NetworkThreatDetectionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NetworkThreatDetectionApi' do
  before do
    # run before each test
    @instance = CloudmersiveSecurityApiClient::NetworkThreatDetectionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NetworkThreatDetectionApi' do
    it 'should create an instance of NetworkThreatDetectionApi' do
      expect(@instance).to be_instance_of(CloudmersiveSecurityApiClient::NetworkThreatDetectionApi)
    end
  end

  # unit tests for network_threat_detection_detect_ssrf_url
  # Check a URL for Server-side Request Forgery (SSRF) threats
  # Checks if an input URL is at risk of being an SSRF (Server-side request forgery) threat or attack.
  # @param request Input URL request
  # @param [Hash] opts the optional parameters
  # @return [UrlSsrfThreatDetectionResponseFull]
  describe 'network_threat_detection_detect_ssrf_url test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for network_threat_detection_is_bot
  # Check if IP address is a Bot client threat
  # Check if the input IP address is a Bot, robot, or otherwise a non-user entity.  Leverages real-time signals to check against known high-probability bots..
  # @param value IP address to check, e.g. \&quot;55.55.55.55\&quot;.  The input is a string so be sure to enclose it in double-quotes.
  # @param [Hash] opts the optional parameters
  # @return [ThreatDetectionBotCheckResponse]
  describe 'network_threat_detection_is_bot test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for network_threat_detection_is_threat
  # Check if IP address is a known threat
  # Check if the input IP address is a known threat IP address.  Checks against known bad IPs, botnets, compromised servers, and other lists of threats.
  # @param value IP address to check, e.g. \&quot;55.55.55.55\&quot;.  The input is a string so be sure to enclose it in double-quotes.
  # @param [Hash] opts the optional parameters
  # @return [IPThreatDetectionResponse]
  describe 'network_threat_detection_is_threat test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for network_threat_detection_is_tor_node
  # Check if IP address is a Tor node server
  # Check if the input IP address is a Tor exit node server.  Tor servers are a type of privacy-preserving technology that can hide the original IP address who makes a request.
  # @param value IP address to check, e.g. \&quot;55.55.55.55\&quot;.  The input is a string so be sure to enclose it in double-quotes.
  # @param [Hash] opts the optional parameters
  # @return [ThreatDetectionTorNodeResponse]
  describe 'network_threat_detection_is_tor_node test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
