=begin
#securityapi

#The security APIs help you detect and block security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-security-api-client/api_client'
require 'cloudmersive-security-api-client/api_error'
require 'cloudmersive-security-api-client/version'
require 'cloudmersive-security-api-client/configuration'

# Models
require 'cloudmersive-security-api-client/models/ip_threat_detection_response'
require 'cloudmersive-security-api-client/models/string_automatic_threat_detection'
require 'cloudmersive-security-api-client/models/string_insecure_deserialization_json_detection'
require 'cloudmersive-security-api-client/models/string_sql_injection_detection_result'
require 'cloudmersive-security-api-client/models/string_xss_protection_result'
require 'cloudmersive-security-api-client/models/string_xxe_detection_result'
require 'cloudmersive-security-api-client/models/threat_detection_bot_check_response'
require 'cloudmersive-security-api-client/models/threat_detection_tor_node_response'
require 'cloudmersive-security-api-client/models/url_ssrf_threat_detection_request_full'
require 'cloudmersive-security-api-client/models/url_ssrf_threat_detection_response_full'

# APIs
require 'cloudmersive-security-api-client/api/content_threat_detection_api'
require 'cloudmersive-security-api-client/api/network_threat_detection_api'

module CloudmersiveSecurityApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveSecurityApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
